### ISSUE TITLE
Suggestion | Add a Javadoc

### ISSUE THREAD

**Issue by CommandCracker8** [Demeng7215/PluginBase#2]
It would be helpful if you generate a Javadoc for this library, it might not just help other users of it, but it might help you as well. When I've generated Javadocs for my code, It's really helped me before. Just a suggestion :D

**Comment by CommandCracker8** [comment]
What do you think of this idea?

**Comment by CommandCracker8** [comment]
Note: If you use IntelliJ, you can generate Javadocs by going to Tools > Generate Javadoc :D

**Comment by CommandCracker8** [comment]
@Demeng7215 , I've created a local version of this repo with a Javadoc, would you like me to fork it and send you the link?

**Comment by demengc** [comment]
I'm looking for a more streamlined solution for this that can automatically update documentation when I push.

**Comment by CommandCracker8** [comment]
Look at maven-javadoc-plugin :D

**Comment by demengc** [comment]
JavaDocs have been uploaded to https://github.com/Demeng7215/PluginBase. Still looking for an automated solution w/ GitHub actions but I don't have the time for that right now, any assistance would be appreciated though :)

**Comment by CommandCracker8** [comment]
https://github.com/marketplace/actions/github-pages-deploy-action

**Comment by CommandCracker8** [comment]
Should help :)

**Comment by CommandCracker8** [comment]
@Demeng7215 I'm pinging you just in case you don't get notified because it's closed
