### ISSUE TITLE
TimeUtils Error

### ISSUE THREAD

**Issue by CommandCracker8** [Demeng7215/PluginBase#4]
On line 52 BaseLoader.getPlugin().getBaseSettings().dateTimeFormat() throws "Cannot find symbol" and on line 58 BaseLoader.getPlugin().getBaseSettings().dateFormat() throws "Cannot find symbol". My IDE is IntelliJ. This is probably my fault, let my know if it is :D

**Comment by demengc** [comment]
Have you tried updating to 1.6.0-SNAPSHOT?

**Comment by CommandCracker8** [comment]
I have updated, I'm on the most recent version. I created a script to update it for me.

**Comment by CommandCracker8** [comment]
I download the version approximately 30 minutes ago by the way.

**Comment by demengc** [comment]
Try Maven -> Reimport Project and Build -> Rebuild Project

**Comment by CommandCracker8** [comment]
I can't find this in IntelliJ, does it help you knowing that I just download the repo, copy the dev folder (from pluginbase-core) into my project? Is there a better way to do it?

**Comment by demengc** [comment]
Can you screenshot the error?

**Comment by CommandCracker8** [comment]
Here :D
![image](https://user-images.githubusercontent.com/68102222/126043516-643339ca-9f0d-48ae-a04b-c58e64d9d3bc.png)

**Comment by CommandCracker8** [comment]
![image](https://user-images.githubusercontent.com/68102222/126043543-f77bf62e-a5d9-4dbc-b2c7-f8f45e7aea55.png)

**Comment by CommandCracker8** [comment]
The error doesn't originate from my code by the way, I'm not even using TimeUtils :\

**Comment by demengc** [comment]
I can only suggest re-downloading the library since the methods do exist...
![image](https://user-images.githubusercontent.com/43016355/126043602-1f1272e0-03ce-4650-99f7-e10dd0fccbb8.png)

**Comment by CommandCracker8** [comment]
It seems the problem is with my downloader script, is there any other way to get the library? Is it, for example, on maven?

**Comment by demengc** [comment]
You can try using JitPack (and selecting the "Commits" tab). https://jitpack.io/#Demeng7215/PluginBase

**Comment by CommandCracker8** [comment]
Thanks! Is there any easy way to make it get the most recent commit?

**Comment by demengc** [comment]
Not that I'm aware of

**Comment by CommandCracker8** [comment]
Okay! I'll see if it works :D

**Comment by CommandCracker8** [comment]
It looks like it's worked, thanks!

**Comment by CommandCracker8** [comment]
I found something else, I've put it in [this](https://github.com/Demeng7215/PluginBase/issues/5) issue, I'll now close this one :D
